### ISSUE TITLE
Direction of effect

### ISSUE THREAD

**Issue by AnthonyGabay** [ACCLAB/dabestr#24] opened 2018-12-10 12:01 UTC
Hi,

I was wondering why the direction of effect is the same regardless of which way around the groups are. See the graphs attached for examples. Both display the same data, but on is "off minus on", while the other is "on minus off". Yet they have the same direction of effect.

Thanks.
![off minus on](https://user-images.githubusercontent.com/43174119/49731439-3d9df200-fc73-11e8-92b8-8bc67be71a07.png)
![on minus off](https://user-images.githubusercontent.com/43174119/49731443-41317900-fc73-11e8-85ce-6e84374844dd.png)

**Comment by josesho** [comment] 2018-12-10 16:00
Hi @AnthonyGabay , yes, this looks like a bug. The control group seems to be assigned to the one that comes first alphabetically. 

I am working on this and hope to have a fix out very soon. For a workaround, please try re-labeling the control groups and test groups such that the control groups will come first alphabetically.

Thanks for your patience and support!

**Comment by AnthonyGabay** [comment] 2018-12-11 14:00
Hi,
Thanks for getting back to me. I love the look of these plots, but I have to say I'm not convinced I trust the output - the mean differences computed are larger than when I compute them manually, sometimes by an order of magnitude. It's possible I don't understand what's going on under the hood with this function, but as far as I understand, the mean difference should be a simple mean of the differences right?

Cheers,
Anthony

**Comment by josesho** [comment] 2018-12-11 15:13
Hi @AnthonyGabay , if you could provide a [minimally reproducible example](http://adv-r.had.co.nz/Reproducibility.html) in a new issue (ie separate from this current issue), that would help greatly in us diagnosing the issue.

Thanks!

**Comment by josesho** [comment] 2018-12-12 02:18
@AnthonyGabay 

Here's a quick experiment on calculating mean differences, and their output

```r
# Set random number generator.
set.seed(123456)

N  <- 30
aa <- rnorm(N, mean = 10,  sd = 2.5)
zz <- rnorm(N, mean = 200, sd = 10)

diff.of.means          <- mean(aa) - mean(zz)

mean.of.diff           <- mean(aa - zz)

# sample() permutates the vector, effectively shuffling its values.
shuffled.diff.of.means <- mean(sample(aa)) - mean(sample(zz))

shuffled.mean.of.diff  <- mean(sample(aa) - sample(zz))

print(c(diff.of.means, mean.of.diff, 
        shuffled.diff.of.means, shuffled.mean.of.diff))
```

which produces

`[1] -186.0837 -186.0837 -186.0837 -186.0837`

So both the difference of means, and the mean of the difference, should give the same value.

**Comment by josesho** [comment] 2018-12-12 09:20
PR #25 (v0.2.0) fixes this. CRAN release is pending; to install v0.2.0 use

```r
devtools::install_github("ACCLAB/dabestr", ref = "v0.2.0")
```

**Closed by josesho** 2018-12-12 09:20 UTC
Labels: bug
